version: 2

sources:
  - name: retail_data              # logical source group
    description: Raw Shopify (online) and Walmart (offline) sales in Snowflake.
    database: RETAIL_PROJECT       # Snowflake database
    schema: PUBLIC                 # schema for raw/staged tables

    tables:
      - name: shopify_orders
        identifier: SHOPIFY_ORDERS # physical table name
        description: Shopify e-commerce orders (raw).

      - name: walmart
        identifier: WALMART        # physical table name
        description: Walmart in-store transactions (raw).

    # freshness:
    #   warn_after: {count: 24, period: hour}
    #   error_after: {count: 48, period: hour}
